### ISSUE TITLE
Mathematical notations and descriptions need to be corrected

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/workshop04#10]
"Variance" is incorrectly referred as "variation" in several slides (including 8, 9, 10, 11, and 12). 

Mathematical notations within the "Variation" slide (currently, number 12) need to be corrected to both variance and coefficient of variation.

**Comment by dschoenig** [comment]
I also recommend that the difference between model notation in R and mathematical notation is better explained. This is often a source of confusion for students, and several slides actually use a mix of both variants in the same "equation".
