### ISSUE TITLE
Content update

### ISSUE THREAD

**Issue by beausoleilmo** [QCBSRworkshops/workshop04#3]
# Suggestions for improvements
- [x] the Markdown presentation contains errors similar to workshop 1 (e.g. the assign operator in R are all messed up!)) 
- [x] some images are not clear at all and can't expect that a student would understand what all of the theory means
- [x] the table of content (at least the one in French) in the presentation is straight up wrong! (it says that we are going to use the anova() function to do an ANOVA (`anova()`)... it's `aov()` (or even `car::Anova()`)!!, but not `anova()`). This was added to the presentation since it wasn't there in the Prezi. And you can use lm() to do a linear model, an ANOVA, or an ANCOVA (depending on the input X variables), but there is strictly no mention anywhere about this.
- [x] The material could be updated to just add a couple of words about manova, polynomial and stepwise function which are useful for different cases where there are multiple Ys (manova), of that the data is not necessarily normal (stepwise function) or that we need to make decision about separation of the data without assumptions in our data (regression trees and classification trees), would be amazing to go through. 
- [x] I felt that slide 17 (French) was impossible to understand. Also, in the wiki, I wasn't able to find a reference to the fact that some functions in R, like `aov()` have a specific way to understand the x variables depending on the situation (especially the type of statistical design of the experiment): if you change the order of the x variables, it might change completely the results of your analysis. Maybe adding a note about this would be interesting and especially how to decide which factor to put first (https://stats.stackexchange.com/questions/13241/the-order-of-variables-in-anova-matters-doesnt-it).

**Comment by estebangongora** [comment]
The different points raised have either been addressed or moved to separate specific issues.
