### ISSUE TITLE
Improve explanation for slide 22

### ISSUE THREAD

**Issue by estebangongora** [QCBSRworkshops/workshop04#8]
The figures shown in this slide are very complex and hard to understand. Including some presenter notes for this slide would really help presenters be aware that it is a complex slide that might need some extra explanations in order to be understood. Alternatively, extra text on the slide could also be of great help.

**Comment by dschoenig** [comment]
I think the slide should only be included if a better figure can be found. The main point of that slide should be that each observation of Y is actually drawn from a normal distribution, its mean being the linear predictor. Getting this across would be enough for one slide.

**Comment by estebangongora** [comment]
I agree that the slide should be kept. It would be a good idea to include an explanation like the one you provided as a presenter notes.

**Comment by LaurieMaynard** [comment]
I added some info in the slides and the presenter notes.
